ALTER TABLE `bms`.`community`
  CHANGE `community_no` `community_no` VARCHAR(50) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '物业标示编号',
  CHANGE `community_name` `community_name` VARCHAR(100) CHARSET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '社区名称',
  CHANGE `community_management_type` `community_management_type` TINYINT(4) NULL COMMENT '管理类型(0简单管理1综合管理)',
  ADD COLUMN `community_address_direction_first_tips` VARCHAR(30) NULL COMMENT '地址方向1提示：东北' AFTER `community_address`,
  ADD COLUMN `community_address_direction_first_value` VARCHAR(300) NULL COMMENT '地址方向1值：历史大厦' AFTER `community_address_direction_first_tips`,
  ADD COLUMN `community_address_direction_second_tips` VARCHAR(30) NULL COMMENT '地址方向2提示：东南' AFTER `community_address_direction_first_value`,
  ADD COLUMN `community_address_direction_second_value` VARCHAR(300) NULL COMMENT '地址方向2值：华发广场' AFTER `community_address_direction_second_tips`,
  ADD COLUMN `community_address_direction_third_tips` VARCHAR(30) NULL COMMENT '地址方向3提示：西北' AFTER `community_address_direction_second_value`,
  ADD COLUMN `community_address_direction_third_value` VARCHAR(300) NULL COMMENT '地址方向3值：历史大厦' AFTER `community_address_direction_third_tips`,
  ADD COLUMN `community_address_direction_fourth_tips` VARCHAR(30) NULL COMMENT '地址方向4提示：西南' AFTER `community_address_direction_third_value`,
  ADD COLUMN `community_address_direction_fourth_value` VARCHAR(300) NULL COMMENT '地址方向4值：历史大厦' AFTER `community_address_direction_fourth_tips`,
  ADD COLUMN `community_cover_area` DECIMAL(12,2) NULL COMMENT '覆盖面积' AFTER `community_area`,
  ADD COLUMN `community_no_cover_area` DECIMAL(12,2) NULL COMMENT '无覆盖面积' AFTER `community_area`,
  ADD COLUMN `community_vertical_area` DECIMAL(12,2) NULL COMMENT '垂直占用空间面积' AFTER `community_no_cover_area`,
  ADD COLUMN `community_shops_area` DECIMAL(12,2) NULL COMMENT '商铺面积' AFTER `community_vertical_area`,
  ADD COLUMN `community_house_area` DECIMAL(12,2) NULL COMMENT '住宅面积' AFTER `community_shops_area`,
  ADD COLUMN `community_shops_count` INT(11) DEFAULT 0 NULL COMMENT '商铺数量' AFTER `community_room_count`;